class Data {
  static dynamic data = {
    "title": "Home",
    "body": {
      "home": {
        "My Programs": {
          "title": "My Programs",
          "subtitle": "Explore to find your new goal",
          "programs": [
            {
              "imageUrl": "https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg",
              "price": "999",
              "title": "Powerlifting HIT",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/men/1.jpg",
              "trainer": "Chris Bumstead",
              "goals": "Muscle Gain",
              "difficulty": "Easy",
              "duration": "3 months",
            },
            {
              "imageUrl": "https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg",
              "price": "1299",
              "title": "CrossFit Max",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/men/3.jpg",
              "trainer": "Liam Thompson",
              "goals": "Endurance",
              "difficulty": "Hard",
              "duration": "4 months",
            },
            {
              "imageUrl": "https://images.pexels.com/photos/1954524/pexels-photo-1954524.jpeg",
              "price": "1099",
              "title": "HIIT Blast",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/men/5.jpg",
              "trainer": "Jake Ryan",
              "goals": "Fat Loss",
              "difficulty": "Medium",
              "duration": "3 months",
            },
            {
              "imageUrl": "https://images.pexels.com/photos/2294361/pexels-photo-2294361.jpeg",
              "price": "899",
              "title": "Strength Camp",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/women/6.jpg",
              "trainer": "Amanda Lee",
              "goals": "Strength Gain",
              "difficulty": "Hard",
              "duration": "2 months",
            },
            {
              "imageUrl": "https://images.pexels.com/photos/414029/pexels-photo-414029.jpeg",
              "price": "699",
              "title": "Pilates Precision",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/women/7.jpg",
              "trainer": "Clara White",
              "goals": "Posture Improvement",
              "difficulty": "Easy",
              "duration": "1.5 months",
            },
          ],
        },
        "Explore Programs": {
          "title": "Explore Programs",
          "subtitle": "Explore to find your new goal",
          "programs": [
            {
              "imageUrl": "https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg",
              "price": "999",
              "title": "Powerlifting HIT",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/men/1.jpg",
              "trainer": "Chris Bumstead",
              "goals": "Muscle Gain",
              "difficulty": "Easy",
              "duration": "3 months",
            },
            {
              "imageUrl": "https://images.pexels.com/photos/1552106/pexels-photo-1552106.jpeg",
              "price": "799",
              "title": "Yoga Flow",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/women/2.jpg",
              "trainer": "Emma Stone",
              "goals": "Flexibility",
              "difficulty": "Medium",
              "duration": "2 months",
            },
            {
              "imageUrl": "https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg",
              "price": "1299",
              "title": "CrossFit Max",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/men/3.jpg",
              "trainer": "Liam Thompson",
              "goals": "Endurance",
              "difficulty": "Hard",
              "duration": "4 months",
            },
            {
              "imageUrl": "https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg",
              "price": "499",
              "title": "Core Crusher",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/women/4.jpg",
              "trainer": "Sophia Green",
              "goals": "Core Strength",
              "difficulty": "Easy",
              "duration": "1 month",
            },
            {
              "imageUrl": "https://images.pexels.com/photos/1954524/pexels-photo-1954524.jpeg",
              "price": "1099",
              "title": "HIIT Blast",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/men/5.jpg",
              "trainer": "Jake Ryan",
              "goals": "Fat Loss",
              "difficulty": "Medium",
              "duration": "3 months",
            },
            {
              "imageUrl": "https://images.pexels.com/photos/2294361/pexels-photo-2294361.jpeg",
              "price": "899",
              "title": "Strength Camp",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/women/6.jpg",
              "trainer": "Amanda Lee",
              "goals": "Strength Gain",
              "difficulty": "Hard",
              "duration": "2 months",
            },
            {
              "imageUrl": "https://images.pexels.com/photos/414029/pexels-photo-414029.jpeg",
              "price": "699",
              "title": "Pilates Precision",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/women/7.jpg",
              "trainer": "Clara White",
              "goals": "Posture Improvement",
              "difficulty": "Easy",
              "duration": "1.5 months",
            },
            {
              "imageUrl": "https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg",
              "price": "1199",
              "title": "Beast Mode",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/men/8.jpg",
              "trainer": "Brandon Carter",
              "goals": "Muscle Gain",
              "difficulty": "Hard",
              "duration": "5 months",
            },
            {
              "imageUrl": "https://images.pexels.com/photos/1552249/pexels-photo-1552249.jpeg",
              "price": "599",
              "title": "Lean & Clean",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/women/9.jpg",
              "trainer": "Nina Torres",
              "goals": "Weight Loss",
              "difficulty": "Medium",
              "duration": "2.5 months",
            },
            {
              "imageUrl": "https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg",
              "price": "999",
              "title": "Bulk Up Fast",
              "trainerProfileUrl": "https://randomuser.me/api/portraits/men/10.jpg",
              "trainer": "David Johnson",
              "goals": "Muscle Gain",
              "difficulty": "Medium",
              "duration": "3 months",
            },
          ],
        },
      },
      "fitness": {
        "title": "Fitness Tracker",
        "subtitle": "Track your workouts and goals"
      },
      "calendar": {
        "title": "Calendar",
        "subtitle": "Your upcoming events"
      }
    }
  };
}
